apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-monkey
  namespace: sre
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-killer
  namespace: sre
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-monkey-binding
  namespace: sre
subjects:
- kind: ServiceAccount
  name: chaos-monkey
  namespace: sre
roleRef:
  kind: Role
  name: pod-killer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-pod-killer
  namespace: sre
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chaos-monkey
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - "kubectl delete pod -l app=api --namespace=sre | head -n 1"
          restartPolicy: OnFailure